import { ProductResType } from "@/types/product";

export const products: ProductResType[] = [
  {
    id: "1",
    name: "Organic Almonds",
    description: "Premium quality organic almonds, rich in nutrients.",
    price: 500,
    discount: 10,
    images: ["/images/almonds.jpg"],
    stock: 50,
    category: { id: "101", name: "Dry Fruits", slug: "dry-fruits" },
    tags: ["healthy", "organic", "protein"],
    collectionType: "fit-food",
    createdAt: "2025-02-23T10:00:00Z",
    updatedAt: "2025-02-23T10:00:00Z",
    thumbnail: "/images/almonds.jpg",
    isVeg: true,


  },
  {
    id: "2",
    name: "Running Shoes",
    description:
      "Lightweight and comfortable running shoes for daily workouts.",
    price: 2999,
    discount: 20,
    images: ["/images/shoes.jpg"],
    stock: 30,
    category: { id: "102", name: "Footwear", slug: "footwear" },
    tags: ["sports", "running", "comfort"],
    collectionType: "trending",
    createdAt: "2025-02-20T12:00:00Z",
    updatedAt: "2025-02-21T12:00:00Z",
    thumbnail: "/images/almonds.jpg",
    isVeg: true,

  },
  {
    id: "3",
    name: "Smart Watch",
    description: "Feature-packed smart watch with heart rate monitor and GPS.",
    price: 5999,
    discount: 15,
    images: ["/images/smartwatch.jpg"],
    stock: 20,
    category: { id: "103", name: "Electronics", slug: "electronics" },
    tags: ["wearable", "tech", "fitness"],
    collectionType: "popular",
    createdAt: "2025-02-18T14:00:00Z",
    updatedAt: "2025-02-19T14:00:00Z",
    thumbnail: "/images/almonds.jpg",
    isVeg: true,

  },
  {
    id: "4",
    name: "Yoga Mat",
    description: "Eco-friendly yoga mat with non-slip surface.",
    price: 1200,
    discount: 10,
    images: ["/images/yogamat.jpg"],
    stock: 40,
    category: { id: "104", name: "Fitness", slug: "fitness" },
    tags: ["exercise", "workout", "eco-friendly"],
    collectionType: "life-style",
    createdAt: "2025-02-22T08:00:00Z",
    updatedAt: "2025-02-22T08:00:00Z",
    thumbnail: "/images/almonds.jpg",
    isVeg: false,

  },
  {
    id: "5",
    name: "Wireless Earbuds",
    description: "Noise-canceling wireless earbuds with long battery life.",
    price: 3499,
    discount: 25,
    images: ["/images/earbuds.jpg"],
    stock: 25,
    category: { id: "105", name: "Audio", slug: "audio" },
    tags: ["music", "wireless", "bass"],
    collectionType: "just-launched",
    createdAt: "2025-02-23T09:30:00Z",
    updatedAt: "2025-02-23T09:30:00Z",
    thumbnail: "/images/almonds.jpg",
    isVeg: false,


  },
];
